CREATE TABLE reservations
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          INTEGER     NOT NULL,
    reservation_date DATE        NOT NULL,
    reservation_time TIME        NOT NULL,
    guests           SMALLINT,
    status           VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    created_at       TIMESTAMP            DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reservations_users_user_id
        FOREIGN KEY (user_id) REFERENCES users (id)
)